{% set name = "h2o-pysparkling-3.0" %}
{% set version = "3.32.1.1-1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h2o_pysparkling_3.0-{{ version }}.tar.gz
  sha256: 487605a12b17d1f4482a14adeb9000e62d8a02545b1750e0c7263414ed28f706

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama >=0.3.8
    - future
    - python >=3.6
    - requests
    - tabulate

test:
  imports:
    - ai
    - ai.h2o
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h2oai/sparkling-water
  summary: Sparkling Water integrates H2O's Fast Scalable Machine Learning with Spark
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cdesouza21
